// flow-typed signature: c10c5d1cdf5e34ef5c96c47f07a4044a
// flow-typed version: <<STUB>>/bezier-easing_v^2.1.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bezier-easing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bezier-easing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bezier-easing/dist/bezier-easing' {
  declare module.exports: any;
}

declare module 'bezier-easing/dist/bezier-easing.min' {
  declare module.exports: any;
}

declare module 'bezier-easing/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bezier-easing/dist/bezier-easing.js' {
  declare module.exports: $Exports<'bezier-easing/dist/bezier-easing'>;
}
declare module 'bezier-easing/dist/bezier-easing.min.js' {
  declare module.exports: $Exports<'bezier-easing/dist/bezier-easing.min'>;
}
declare module 'bezier-easing/src/index' {
  declare module.exports: $Exports<'bezier-easing/src'>;
}
declare module 'bezier-easing/src/index.js' {
  declare module.exports: $Exports<'bezier-easing/src'>;
}
